spring:
  application:
    name: panel
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/panel}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.mariadb.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
panel:
  security:
    jwt:
      secret: ${JWT_SECRET:12345678901234567890123456789012}
      expiration: ${JWT_EXPIRATION:86400000}
    cors:
      allow-credentials: true
      allowed-origins: ${CORS_ALLOWED_ORIGINS:[http://localhost:5173]}
      allowed-methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed-headers: ["*"]
      exposed-headers: [Authorization]
springdoc:
  api-docs:
    enabled: true